apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', views.login, name = 'login'),
    path('403/', views.cuowu1, name='cuowu1'),
    path('404/', views.cuowu2, name='cuowu2'),
    path('500/', views.cuowu3, name='cuowu3'),
    path('huodong/', views.huodong, name='huodong'),
    path('kebiao/', views.kebiao, name='kebiao'),
    path('zhuce/', views.zhuce, name='zhuce'),
    path('room/', views.room, name='room'),
    path('yuyue/', views.yuyue, name='yuyue'),
    path('zhongxin/', views.zhongxin, name='zhongxin'),
]

jiaoshi/urls.py
# _*_ encoding:utf-8 _*_
"""jiaoshi URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
#from django.contrib import admin
from django.urls import path,include

#from users import views
#from django.conf.urls import url
from django.contrib import admin
#from django.views.generic import TemplateView
#from users.views import login
#from users.views import cuowu1
#from users.views import cuowu2
#from users.views import cuowu3
#from users.views import huodong
#from users.views import zhuce
#from users.views import index
#from users.views import kebiao
#from users.views import room
#from users.views import zhongxin


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index , name ='zhuye')
    path('', include('users.urls', namespace = 'users'))
    #path('^403/', cuowu1, name='403'),
    #path('login/', login, name='login'),
    #path('zhongxin/', zhongxin, name='zhongxin'),
    #path('kebiao/', kebiao, name='kebiao'),
   # path('regist/', zhuce, name='zhuce'),
   # path('room/', room, name='room'),
   # path('huodong/', huodong, name='huodong'),
   # path('404/', cuowu2, name='404'),
   # path('500/', cuowu3, name='500'),
]


apps/activites/models.py
# _*_ encoding:utf-8 _*_

from __future__ import unicode_literals

from datetime import datetime

from django.db import models

# Create your models here.


class Activity(models.Model):
    data = models.DateField(verbose_name=u"日期", null=True, blank=True)
    time = models.CharField(choices=(('morning', u'上午'), ('afternoon', u'下午'), ('night', u'晚上')), max_length= 100, default='morning')
    class_num = models.CharField(max_length=10,verbose_name=u"教室", default=0)
    order = models.CharField(max_length=100, verbose_name=u'预约', default=0)

    class Meta:
        verbose_name = u"活动信息"
        verbose_name_plural = verbose_name

apps/empty/models.py
from django.db import models

# Create your models here.

apps/operations/models.py
# _*_ encoding:utf-8 _*_
from __future__ import unicode_literals

from datetime import datetime

from django.db import models

# Create your models here.


class UserMessage(models.Model):
    user = models.IntegerField(default=0, verbose_name=u'接收用户')
    message = models.CharField(max_length=500, verbose_name=u"消息内容")
    has_read = models.BooleanField(default=False, verbose_name=u"是否已读")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = u"用户信息"
        verbose_name_plural=verbose_name

apps/users/models.py
# _*_ encoding:utf-8 _*_
from __future__ import unicode_literals

from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class UserProfile(AbstractUser):
    nike_name = models.CharField(max_length=50, verbose_name=u"姓名")
    gender = models.CharField(max_length=10, choices=(("male", u'男'), ("female", u'女')), default="female")
    mobile = models.CharField(max_length=11, null=True, blank=True)

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.username

apps/activites/views.py
from django.shortcuts import render

# Create your views here.

apps/empty/views.py
from django.shortcuts import render

# Create your views here.

apps/operations/views.py
from django.shortcuts import render

# Create your views here.

apps/users/views.py
from django.shortcuts import render

# Create your views here.

# _*_ encoding:utf-8 _*_
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q

from .models import UserProfile
# Create your views here.
from django.shortcuts import render
from django.contrib.auth import authenticate, login


class CustomBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username)|Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


def login(request):
    if request.method == 'POST':
        user_name = request.POST.get("username", '')
        pass_word = request.POST.get("password", '')
        user = authenticate(username=user_name, password=pass_word)
        if user is not None:
            login(request, user)
            return render(request, 'index.html')
        else:
            return render(request, 'login.html', {'msg': '用户名或者密码错误！'})
    elif request.method == "GET":
        return render(request, 'login.html', {})


def cuowu1(request):
    return render(request, '403.html', {})


def cuowu2(request):
    return render(request, '404.html', {})


def cuowu3(request):
    return render(request, '500.html', {})


def huodong(request):
    return render(request, 'huodong.html', {})


def index(request):
    return render(request, 'index.html')


def kebiao(request):
    return render(request, 'kebiao.html', {})


def zhuce(request):
    return render(request, 'regist.html', {})


def room(request):
    return render(request, 'room.html', {})


def yuyue(request):
    return render(request, 'yuyue.html', {})


def zhongxin(request):
    return render(request, 'zhongxin.html', {})

templates/index.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>教室资源管理</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
    
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>110</b></p></div>
					<!--登录后跳转-->

                        
                        <!-- <a style="color:white" class="fr registerbtn" href="register.html">注册</a> -->
                        <!-- <a style="color:white" class="fr loginbtn" href="login.html">登录</a>  -->
						
						<div class="personal">
                            <dl class="user fr">
                                <dd>bobby<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="/static/media/image/2016/12/default_big_14.png"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="/static/media/image/2016/12/default_big_14.png"/></dt>
	                                <dd>
	                                    <h2>django</h2>
	                                    <p>你好</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="fr" href="/logout/">退出</a>
                                </div>
                            </div>
                        </div>


				</div>
			</div>

            
            
			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li class="active" ><a href="{%  url 'users:index' %}">首页</a></li>
							<li >
								<a href="{%  url 'users:huodong' %}">
									活动<img class="hot" src="/static/images/nav_hot.png">
								</a>
							</li>
							<li >
								<a href="{%  url 'users:room' %}">空闲教室查询</a>
							</li>
                            <li><a >教室预约</a></li>
							<li><a href="{%  url 'users:zhongxin' %}">进入个人中心</a></li>
							<div style="float: right;">
							<li> <a class="personcenter fl" href="{%  url 'users:login' %}">登录</a></li>
							<li> <a class="personcenter fl" href="#">注册</a></li>
							</div>
						</ul>
					</div>
				</div>
			</nav>
            
    </header>
</section>
<!--crumbs start-->



    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            
                            <li>
                                    <a href="http://www.imooc.com">
                                        <img width="1200" height="675" src="/static/media/banner/2016/11/建大1.jpg" />
                                    </a>
                                </li>
                            
                            <li>
                                    <a href="http://www.projectsedu.com">
                                        <img width="1200" height="675" src="/static/media/banner/2016/11/建大21.jpg" />
                                    </a>
                                </li>
                            
                            <li>
                                    <a href="http://www.projectsedu.com">
                                        <img width="1200" height="675" src="/static/media/banner/2016/11/建达.jpg" />
                                    </a>
                                </li>
                            
                            <li>
                                    <a href="http://www.projectsedu.com">
                                        <img width="1200" height="675" src="/static/media/banner/2016/11/建大6.jpg" />
                                    </a>
                                </li>
                            
                            <li>
                                 <a href="http://www.projectsedu.com">
                                        <img width="1200" height="675" src="/static/media/banner/2016/11/建大5.jpg" />
                                    </a>
                                </li>
                            

						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/img/feature1.png"/>
					<p class="center">建大美景</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">建大风采</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">易海学子</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/img/feature4.png"/>
					<p class="center">九月美景</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>建大活动</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/活动11.jpg"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="course-list.html">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                    
                                    <li>
                                        <a href="course-detail.html">
                                            <img width="470" height="300" style="height:300px" src="/static/media/courses/2016/12/活动10.jpg" />
                                        </a>
                                    </li>
                                    
                                    <li>
                                        <a href="course-detail.html">
                                            <img width="470" height="300" style="height:300px" src="/static/media/courses/2016/12/活动12.jpg" />
                                        </a>
                                    </li>
                                    
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            
                            <div class="module1_3 box">
                                <a href="course-detail.html">
                                    <img width="233" height="300px" style="height:300px" src="/static/media/courses/2016/11/活动2.jpg"/>
                                </a>
                          
                            </div>
                            
                            <div class="module1_4 box">
                                <a href="course-detail.html">
                                    <img width="233" height="300px" style="height:300px" src="/static/media/courses/2016/11/活动4.jpg"/>
                                </a>
                                
                               
                            </div>
                            
                            <div class="module1_5 box">
                                <a href="course-detail.html">
                                    <img width="233" height="300px" src="/static/media/courses/2016/11/活动9.jpg" style="height:300px"/>
                                </a>
                               
                            </div>
                            
                            <div class="module1_6 box">
                                <a href="course-detail.html">
                                    <img width="233" height="300px" src="/static/media/courses/2016/11/活动8.jpg" style="height:300px"/>
                                </a>
                               
                                
                            </div>
                            
                            <div class="module1_7 box">
                                <a href="course-detail.html">
                                    <img width="233" height="300px" style="height:300px" src="/static/media/courses/2016/11/活动10.jpg"/>
                                </a>
                                
                                
                            </div>
                            
                            <div class="module1_8 box">
                                <a href="course-detail.html">
                                    <img width="233" height="300px" style="height:300px" src="/static/media/courses/2016/11/活动7.jpg"/>
                                </a>
                               
                                
                            </div>
                            
					</div>
				</div>
			</div>
		</div>
	</section>
<script src="/static/js/selectUi.js" type='text/javascript'></script>
<script src="/static/js/deco-common.js" type='text/javascript'></script>
<script type="text/javascript" src="/static/js/plugins/laydate/laydate.js"></script>
<script src="/static/js/plugins/layer/layer.js"></script>
<script src="/static/js/plugins/queryCity/js/public.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/plugins/jquery.scrollLoading.js"  type="text/javascript"></script>
<script src="/static/js/deco-common.js"  type="text/javascript"></script>

</body>
</html>

templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>登录 </title>
<style type="text/css">
html,body{margin:0;padding:0;width:100%;}
body{font-size:12px;font-family: "微软雅黑";color:#333;line-height:160%;background: url(/static/img/login-bg.jpg) center top repeat-x #FFF;height:100%;}
p,ul,.name,.pwd,dd,h1,h2,h3,form,input,select,textarea{margin:0;padding:0;border:0;font-family:"微软雅黑";line-height:150%;}
ul,li{list-style:none;}
div,p{word-wrap: break-word;}
img{border: none;}
input,button,select,textarea{outline:none}

/*login*/
.login{padding:1px 0 0 0;background:url(img/true (1).jpg)uucenter top no-repeat #FFF;padding:150px 0 0 0;}
.login input.submit{border:none;font-weight:bold;color:#FFF;margin:25px 0 0 150px;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px;-webkit-box-shadow: #CCC 0px 0px 5px;-moz-box-shadow: #CCC 0px 0px 5px;box-shadow: #CCC 0px 0px 5px;background: #31b6e7;cursor: pointer;}
.login input.submit:hover{background:#ff9229;}
.login input.submit{padding:6px 20px;}
.login .box{position:relative;z-index:100;margin:0 auto;width:700px;height:320px;background:url(/static/img/login.png) center top no-repeat;}
.login .log{position:relative;width:370px;height:260px;margin:0 auto;padding:90px 0 0 20px;}
.login .logo{height:85px;position:absolute;top:15px;left:180px;background:url(/static/img/logo-login.png) no-repeat;width:350px;height:50px;}
.login label{display:inline-block;width:70px;text-align:right;padding-right:20px;vertical-align:middle;}
.login .name{padding:10px 5px;font-size:14px;}
.login .pwd{padding:10px 5px;font-size:14px;}
.login .alt{position:absolute;top:43px;left:260px;font-size:20px;}
.login .text{filter:alpha(opacity=80);-moz-opacity:0.8;opacity:0.8;}
.login .copyright{position:absolute;left:0;width:100%;bottom:-40px;text-align:center;color:#AAA;}
.login .air-balloon{position:absolute;top:-100px;left:-100px;z-index:50;}
.login .air-balloon.ab-1{width:43px;height:78px;background:url(/static/img/air-balloon-1.png) no-repeat;}
.login .air-balloon.ab-2{width:24px;height:31px;background:url(/static/img/air-balloon-2.png)) no-repeat;}
.login .footer{position: fixed;left:0;bottom:0;z-index:-1;width:100%;height:198px;background:url(/static/img/login-foot.jpg) center bottom repeat-x;}
.text{border:1px solid #CCC;padding:5px;background-color:#FCFCFC;line-height:14px;width:220px;font-size:12px;-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;-webkit-box-shadow: #CCC 0px 0px 5px;-moz-box-shadow: #CCC 0px 0px 5px;box-shadow: #CCC 0px 0px 5px;border:1px solid #CCC;font-size:12px;}
.text:focus{border:1px solid #31b6e7;background-color:#FFF;-webkit-box-shadow: #CCC 0px 0px 5px;-moz-box-shadow: #CCC 0px 0px 5px;box-shadow: #0178a4 0px 0px 5px;}
.text:hover{background-color:#FFF;}
</style>
</head>
<body>


<div class="login">
    <div class="box png">
		<div class="logo png"></div>
		<div class="input">
			<form id="check" action="#" method="post">  
			<div class="log">
				<div class="name">
					<label>用户名</label><input type="text" class="text" id="value_1" placeholder="用户名" name="value_1" tabindex="1">
				</div>
				<div class="pwd">
					<label>密　码</label><input type="password" class="text" id="value_2" placeholder="密码" name="value_2" tabindex="2">
					<input type="button" class="submit" tabindex="3" value="登录">
					<div class="check"></div>
				</div>
				<div class="tip"></div>
			</div>
			</form>
		</div>
	</div>
    <div class="air-balloon ab-1 png"></div>
	<div class="air-balloon ab-2 png"></div>
    <div class="footer"></div>
</div>

<script type="text/javascript" src="/static/js/jQuery.js"></script>
<script type="text/javascript" src="/static/js/fun.base.js"></script>
<script type="text/javascript" src="/static/js/script.js"></script>


<!--[if IE 6]>
<script src="js/DD_belatedPNG.js" type="text/javascript"></script>
<script>DD_belatedPNG.fix('.png')</script>
<![endif]-->
<div style="text-align:center;margin:50px 0; font:normal 14px/24px 'MicroSoft YaHei';">
</div>
</body>
</html>

templates/regist.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>登录 </title>
<style type="text/css">
html,body{margin:0;padding:0;width:100%;}
body{font-size:12px;font-family: "微软雅黑";color:#333;line-height:160%;background: url(/static/img/login-bg.jpg) center top repeat-x #FFF;height:100%;}
p,ul,.name,.pwd,dd,h1,h2,h3,form,input,select,textarea{margin:0;padding:0;border:0;font-family:"微软雅黑";line-height:150%;}
ul,li{list-style:none;}
div,p{word-wrap: break-word;}
img{border: none;}
input,button,select,textarea{outline:none}

/*login*/
.login{padding:1px 0 0 0;background:url(/static/img/true (1).jpg)uucenter top no-repeat #FFF;padding:150px 0 0 0;}
.login input.submit{border:none;font-weight:bold;color:#FFF;margin:25px 0 0 150px;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px;-webkit-box-shadow: #CCC 0px 0px 5px;-moz-box-shadow: #CCC 0px 0px 5px;box-shadow: #CCC 0px 0px 5px;background: #31b6e7;cursor: pointer;}
.login input.submit:hover{background:#ff9229;}
.login input.submit{padding:6px 20px;}
.login .box{position:relative;z-index:100;margin:0 auto;width:700px;height:320px;background:url(/static/img/login.png) center top no-repeat;}
.login .log{position:relative;width:370px;height:260px;margin:0 auto;padding:90px 0 0 20px;}
.login .logo{height:85px;position:absolute;top:15px;left:180px;background:url(/static/img/logo-login.png) no-repeat;width:350px;height:50px;}
.login label{display:inline-block;width:70px;text-align:right;padding-right:20px;vertical-align:middle;}
.login .name{padding:10px 5px;font-size:14px;}
.login .pwd{padding:10px 5px;font-size:14px;}
.login .alt{position:absolute;top:43px;left:260px;font-size:20px;}
.login .text{filter:alpha(opacity=80);-moz-opacity:0.8;opacity:0.8;}
.login .copyright{position:absolute;left:0;width:100%;bottom:-40px;text-align:center;color:#AAA;}
.login .air-balloon{position:absolute;top:-100px;left:-100px;z-index:50;}
.login .air-balloon.ab-1{width:43px;height:78px;background:url(/static/img/air-balloon-1.png) no-repeat;}
.login .air-balloon.ab-2{width:24px;height:31px;background:url(/static/img/air-balloon-2.png)) no-repeat;}
.login .footer{position: fixed;left:0;bottom:0;z-index:-1;width:100%;height:198px;background:url(/static/img/login-foot.jpg) center bottom repeat-x;}
.text{border:1px solid #CCC;padding:5px;background-color:#FCFCFC;line-height:14px;width:220px;font-size:12px;-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;-webkit-box-shadow: #CCC 0px 0px 5px;-moz-box-shadow: #CCC 0px 0px 5px;box-shadow: #CCC 0px 0px 5px;border:1px solid #CCC;font-size:12px;}
.text:focus{border:1px solid #31b6e7;background-color:#FFF;-webkit-box-shadow: #CCC 0px 0px 5px;-moz-box-shadow: #CCC 0px 0px 5px;box-shadow: #0178a4 0px 0px 5px;}
.text:hover{background-color:#FFF;}
</style>
</head>
<body>


<div class="login">
    <div class="box png">
		<div class="logo png"></div>
		<div class="input">
			<div class="log">
				<div class="name">
					<label>用户名</label><input type="text" class="text" id="value_1" placeholder="用户名" name="value_1" tabindex="1">
				</div>
				<div class="pwd">
					<label>密　码</label><input type="password" class="text" id="value_2" placeholder="密码" name="value_2" tabindex="2">
					<label style="margin-top: 5px;">确认密码</label><input type="password" class="text" id="value_2" placeholder="密码" name="value_2" tabindex="2"  style="margin-top: 15px;">
					<input type="button" class="submit" tabindex="3" value="注册">
					<div class="check"></div>
				</div>
				<div class="tip"></div>
			</div>
		</div>
	</div>
    <div class="air-balloon ab-1 png"></div>
	<div class="air-balloon ab-2 png"></div>
    <div class="footer"></div>
</div>

<script type="text/javascript" src="/static/js/jQuery.js"></script>
<script type="text/javascript" src="/static/js/fun.base.js"></script>
<script type="text/javascript" src="/static/js/script.js"></script>


<!--[if IE 6]>
<script src="js/DD_belatedPNG.js" type="text/javascript"></script>
<script>DD_belatedPNG.fix('.png')</script>
<![endif]-->
<div style="text-align:center;margin:50px 0; font:normal 14px/24px 'MicroSoft YaHei';">
</div>
</body>
</html>

templates/room.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<style type="text/css">
			#biaotilan{
				height:50px;
			    width:1200px;
			    border: #007FFF solid 1px;
		     	background-color: #0082DF;
			}
				#zhuti{
				width: 1200px;
				height: 600px;
				border: #31B6E7 solid 1px;
			}
			#left{
				width: 300px;
				height: 600px;
				border: #31B6E7 solid 1px;
				float: left;
			}
			#right{
				width: 895px;
				height: 600px;
				border: #31B6E7 solid 1px;
				float: left;
			}
			
		</style>
	</head>
	<body>
    	<div id="biaotilan">
    		<table height="100%" width="100%" border="1px" cellspacing="0px">
    			<tr>
    				<td width="25%" align="center">
    					<a href="{%  url 'index' %}" style=" color: coral;">返回</a>
    				</td>
    				<td width="50%" style="text-align: center; ">
    				     <p>查询空闲教室</p>
    				</td>
    				<td width="25%" style="text-align: center; ">
    					<a href="{%  url 'yuyue' %}" style=" color: coral;">预约</a>
    				</td>
    			</tr>
    		</table>
    	</div>
    	<div id="zhuti">
			<div id="left">
				<p>日期<input style="margin-left: 10px; margin-top: 150px; " placeholder="dd-dd"/></p>
				<p>时间<input style="margin-left: 10px; margin-top: 50px; "  placeholder="00:00-00:00"/></p>
				<p><input type="submit" value="提交" style="margin-left: 50px;  " ></input></p>
			</div>
			<div id="right">
				<div class="xianshi">
					<iframe name="xian" style="width: 890px; height:600px; " ></iframe>
				</div>
			</div>
		</div>
    </body>
</html>

templates/yuyue.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<style type="text/css">
			#biaotilan{
				height:50px;
			    width:1200px;
			    border: #007FFF solid 1px;
		     	background-color: #0082DF;
			}
				#zhuti{
				width: 1200px;
				height: 600px;
				border: #31B6E7 solid 1px;
			}
			#left{
				width: 300px;
				height: 600px;
				border: #31B6E7 solid 1px;
				float: left;
			}
			#right{
				width: 895px;
				height: 600px;
				border: #31B6E7 solid 1px;
				float: left;
			}
			
		</style>
	</head>
	<body>
    	<div id="biaotilan">
    		<table height="100%" width="100%" border="1px" cellspacing="0px">
    			<tr>
    				<td width="25%" align="center">
    					<a href="{%  url 'index' %}" style=" color: coral;">返回</a>
    				</td>
    				<td width="50%" style="text-align: center; ">
    				     <p>教室预约</p>
    				</td>
    				<td width="25%" style="text-align: center; ">
    					<a href="#" style=" color: coral;">我的预约</a>
    				</td>
    			</tr>
    		</table>
    	</div>
    	<div id="zhuti">
			<div id="left">
				<p>教室号<input type="text" style="margin-left: 10px; margin-top: 150px; " placeholder="----"/></p>
				<p>预约时长<input type="text" style="margin-left: 10px; margin-top: 50px; "  placeholder="00:00-00:00"/></p>
				<p>预约理由<input type="text" style="margin-left: 10px; margin-top: 50px; width: 100px; height: 60px;"  placeholder="00:00-00:00"/></p>
				<p><input type="submit" value="提交" style="margin-left: 50px;  " ></input></p>
			</div>
			<div id="right">
				<div class="xianshi">
					<iframe name="xian" style="width: 890px; height:600px; " ></iframe>
				</div>
			</div>
		</div>
    </body>
</html>
